
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
  labels:
    name: homeassistant
    
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-retain
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 2Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 2Gi
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: homeassistant-config-vol
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
        - name: homeassistant-data-vol
          persistentVolumeClaim:
            claimName: homeassistant-data-pvc
      containers:
        - name: homeassistant
          image: 'homeassistant/home-assistant:stable'
          resources:
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
            - name: mdns
              containerPort: 5353            # mDNS discovery port
              protocol: UDP 
            - name: upnp
              containerPort: 1900            # UPnP discovery port #             
              protocol: UDP                 
          volumeMounts:
            - name: homeassistant-config-vol
              mountPath: /config
            - name: homeassistant-data-vol
              mountPath: /etc/ha-data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      # hostNetwork: true
      terminationGracePeriodSeconds: 30
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 192.168.1.3
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600    
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - port: 8123
      protocol: TCP
  type: LoadBalancer
  
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-network-service
  namespace: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - name: mdns
      port: 5353
      protocol: UDP
    - name: upnp
      port: 1900
      protocol: UDP
  type: LoadBalancer  
---
