
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
  labels:
    name: homeassistant
    
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-retain
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 2Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-data-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 2Gi
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: homeassistant-config-vol
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
        - name: homeassistant-data-vol
          persistentVolumeClaim:
            claimName: homeassistant-data-pvc
      containers:
        - name: homeassistant
          image: 'homeassistant/home-assistant:stable'
          resources:
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: homeassistant-config-vol
              mountPath: /config
            - name: homeassistant-data-vol
              mountPath: /etc/ha-data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: true
      terminationGracePeriodSeconds: 30
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 192.168.1.2
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600    

---

kind: Service
apiVersion: v1
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
    kubernetes.io/name: homeassistant
spec:
  ports:
    - name: homeassistant
      protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30438
  selector:
    app: homeassistant
  type: NodePort
  sessionAffinity: None
  
