
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
  labels:
    name: homeassistant
    
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-retain
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 2Gi
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1  
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: homeassistant-nfs-config-vol
          nfs:
            server: 192.168.1.114
            path: /volume2/home-infra/homeassistant/config
      containers:
        - name: homeassistant
          image: 'homeassistant/home-assistant:stable'
          resources:
          ports:
            - containerPort: 8123
              protocol: TCP
            - containerPort: 5353            # mDNS discovery port
              protocol: UDP 
            - containerPort: 1900            # UPnP discovery port #             
              protocol: UDP                 
          volumeMounts:
            - name: homeassistant-config-vol
              mountPath: /config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      # hostNetwork: true
      terminationGracePeriodSeconds: 30
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 192.168.1.3
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600    
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123
  type: LoadBalancer
  
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-network-service
  namespace: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - name: mdns
      port: 5353
      protocol: UDP
      targetPort: 5353
    - name: upnp
      port: 1900
      protocol: UDP
      targetPort: 1900
  type: LoadBalancer  
---
