apiVersion: batch/v1
kind: CronJob
metadata:
  name: image-prepull-cron
spec:
  schedule: "0 3 * * *"  # Run at 3 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prepull
            image: 'homeassistant/home-assistant:stable'
            command: ["true"]
          restartPolicy: Never
