kind: Namespace
apiVersion: v1
metadata:
  name: unifi
  labels:
    name: unifi

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-retain
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-log-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 2Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: unifi-controller
  name: unifi-controller
  namespace: unifi
spec:
  replicas: 1
  serviceName: unifi-controller
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unifi-controller
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Bangkok
            - name: MEM_LIMIT
              value: 1024M
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          image: jacobalberty/unifi:v7.3.83
          name: unifi-controller
          ports:
            - containerPort: 3478
              protocol: UDP
            - containerPort: 10001
              protocol: UDP
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 8443
            - containerPort: 8843
            - containerPort: 8880
            - containerPort: 6789
          volumeMounts:
            - mountPath: unifi/data
              name: unifi-data-vol
            - mountPath: unifi/log
              name: unifi-log-vol
      restartPolicy: Always
      volumes:
        - name: unifi-data-vol
          persistentVolumeClaim:
            claimName: unifi-data-pvc
        - name: unifi-log-vol
          persistentVolumeClaim:
            claimName: unifi-log-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: unifi-lb-tcp
  namespace: unifi
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller 
  ports:
    - name: device-comm
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: default-console
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: secure-redirect
      port: 8843
      protocol: TCP
      targetPort: 8843
    - name: http-redirect
      port: 8880
      protocol: TCP
      targetPort: 8880
    - name: speedtest
      port: 6789
      protocol: TCP
      targetPort: 6789

---
apiVersion: v1
kind: Service
metadata:
  name: unifi-lb-udp
  namespace: unifi
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller 
  ports:
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: unifi-disc
      port: 10001
      protocol: UDP
      targetPort: 10001
    - name: unifi-disc-l2
      port: 1900
      protocol: UDP
      targetPort: 1900

---